import React from 'react';
import { Link } from 'react-router-dom';

function Disclosures() {
  return (
    <div className="card" style={{ maxWidth: '880px', margin: '0 auto' }}>
      <h1 style={{ marginBottom: '1rem' }}>Disclosures</h1>

      <section style={{ marginBottom: '1.75rem' }}>
        <h2 style={{ fontSize: '1.25rem' }}>AI-Generated Content</h2>
        <p style={{ marginBottom: '0.75rem' }}>
          All summaries, predictions, root-cause analyses, thread intelligence, and country briefings are generated
          by large language models. They are provided for informational and educational purposes only.
        </p>
        <p style={{ marginBottom: '0.75rem' }}>
          <strong>This content does not constitute financial, investment, legal, political, security, or professional
          advice of any kind.</strong> Forward-looking statements and forecasts reflect AI-generated analysis of
          available information and are not guarantees or predictions of future events. Actual outcomes may differ
          materially from anything described on this platform.
        </p>
        <p style={{ marginBottom: '0.75rem' }}>
          You should not rely solely on content from this platform when making business, investment, policy, or
          security decisions. Always verify information independently through primary sources and consult qualified
          professionals where appropriate.
        </p>
        <p>
          Global Perspectives assumes no liability for decisions made based on AI-generated content. Use of this
          platform constitutes acceptance of this disclaimer.
        </p>
      </section>

      <section style={{ marginBottom: '1.75rem' }}>
        <h2 style={{ fontSize: '1.25rem' }}>Limitation of Liability</h2>
        <p style={{ marginBottom: '0.75rem' }}>
          To the maximum extent permitted by applicable law, Global Perspectives and its operators shall not be
          liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use
          of this platform or reliance on any content it provides.
        </p>
        <p>
          The platform is provided "as is" without warranties of any kind, express or implied, including but not
          limited to accuracy, completeness, timeliness, or fitness for a particular purpose.
        </p>
      </section>

      <section style={{ marginBottom: '1.75rem' }}>
        <h2 style={{ fontSize: '1.25rem' }}>Data Sources</h2>
        <ul style={{ paddingLeft: '1.25rem' }}>
          <li>Topic detection and AI analysis: DeepSeek V4 and Google Gemini, using globally syndicated publishers and Brave Search.</li>
          <li>Geocoding and map layers: Google Maps Platform.</li>
        </ul>
        <p style={{ marginTop: '0.75rem' }}>
          Source articles are linked for reference. Global Perspectives does not reproduce full article text and
          is not responsible for the accuracy or availability of third-party source content.
        </p>
      </section>

      <section style={{ marginBottom: '1.75rem' }}>
        <h2 style={{ fontSize: '1.25rem' }}>Economic Disruption Analysis</h2>
        <p style={{ marginBottom: '0.75rem' }}>
          <strong>This is not investment advice.</strong> The Economic Disruption layer attempts to identify
          which financial instruments are being repriced by ongoing news threads. It is provided for
          analytical context only, not for trading, investment, or portfolio decisions.
        </p>
        <p style={{ marginBottom: '0.75rem' }}>
          <strong>Methodology — what is generated by AI vs. computed:</strong>
        </p>
        <ul style={{ paddingLeft: '1.25rem', marginBottom: '0.75rem' }}>
          <li><strong>AI generates:</strong> direction (up/down/mixed), severity bands (minor/moderate/severe),
            magnitude bands (small/moderate/large), 1–2 paragraph mechanism narrative, historical-analog selection,
            and the list of relevant instruments — chosen from a fixed allowlist.</li>
          <li><strong>We compute from market data, not AI:</strong> actual price levels, asOf timestamps, and any
            observed % moves. Prices are snapshotted from public sources (Frankfurter / FRED / Stooq / World Bank).</li>
          <li><strong>Severity is never a percentage.</strong> We do not publish point estimates of price impact
            because LLMs are documented to hallucinate financial point estimates. Severity is expressed as a
            qualitative band only.</li>
          <li><strong>Every claim cites a topicId</strong> from the underlying news thread. Claims that cannot
            be cited to specific articles are dropped server-side.</li>
          <li><strong>Closed instrument allowlist.</strong> The AI may only reference instruments from a curated
            list of commodities, indices, ETFs, sovereign yields, FX pairs, and select crypto. Anything else
            is filtered out.</li>
          <li><strong>Historical analogs show realized past moves, not predictions.</strong> When an analog event
            is cited (e.g. "2019 Abqaiq attack"), we describe what historically happened — we do not predict the
            current outcome will match.</li>
        </ul>
        <p style={{ marginBottom: '0.75rem' }}>
          <strong>Limitations.</strong> Most short-term market moves are driven by macro flows (Fed policy, positioning,
          liquidity), not by the geopolitical headline of the day. Treat any "instrument moved on news X" framing
          as <em>consistent with</em>, not <em>caused by</em>. Outputs may be stale by hours; check the
          <code> asOf </code>timestamp on every record. References to academic methodology include
          Caldara &amp; Iacoviello (2022) Geopolitical Risk Index and the BlackRock Investment Institute's
          Geopolitical Risk Dashboard.
        </p>
        <p style={{ marginBottom: '0.75rem' }}>
          <strong>Automated quality check (LLM-as-judge).</strong> After every Economic Disruption record is
          generated, a separate model (Gemini 2.5 Flash, different family from the author model) re-reads the
          record and scores it 1–5 on five axes: <em>coherence</em>, <em>citation fidelity</em>,
          <em> analog match</em>, <em>severity calibration</em>, and <em>no-BS</em> (no unsupported point
          estimates, no fabricated tickers, no hallucinated mechanisms). If any axis scores ≤ 2 the record is
          tagged <code>auto-judged: review</code> and surfaces with a warning chip across the site. This is a
          first-pass filter — it does not replace human review and can itself be wrong. Methodology adapted from
          Zheng et al., <em>Judging LLM-as-a-Judge</em> (NeurIPS 2023). Aggregate scores are reviewed weekly.
        </p>
      </section>

      <section style={{ marginBottom: '1.75rem' }}>
        <h2 style={{ fontSize: '1.25rem' }}>Accuracy &amp; Bias</h2>
        <p>
          AI systems can reflect the limitations and biases of their training data and source material. Regions
          with limited media coverage may appear underrepresented. AI-generated analysis may contain errors,
          omissions, or outdated information. Global Perspectives makes no representation that content is complete,
          current, or free from inaccuracy.
        </p>
      </section>

      <section style={{ marginBottom: '1.75rem' }}>
        <h2 style={{ fontSize: '1.25rem' }}>Access &amp; Pricing</h2>
        <p>
          All published intelligence is <strong>free and public to read</strong> — every feature (today's topics,
          the interactive map, narrative archive, thread and country intelligence, economic analysis, daily and
          weekly briefs, and the forecast track record) is fully open with no account or payment required to read.
          An optional account (email magic link or Google sign-in) is free and enables saving items and notification
          preferences.
        </p>
        <p>
          An optional <strong>membership</strong> doesn&apos;t paywall reading — every analysis stays free. It adds
          <strong> depth</strong>: the full history of how each country and thread read has changed (non-members see the
          latest correction on each), email alerts when a country you follow materially changes, and running the{' '}
          <Link to="/analyze">Analysis Studio</Link> on our own servers (no API key of your own needed). See{' '}
          <Link to="/membership">Membership</Link> for current availability and pricing; payments, when active, are
          processed by Polar as Merchant of Record.
        </p>
      </section>

      <section style={{ marginBottom: '1.75rem' }}>
        <h2 style={{ fontSize: '1.25rem' }}>Contact</h2>
        <p>
          For account issues or general inquiries:<br />
          Email: <a href="mailto:globalperspectives.app@gmail.com">globalperspectives.app@gmail.com</a>
        </p>
        <p>
          Business name: Global Perspectives
        </p>
      </section>

      <section>
        <h2 style={{ fontSize: '1.25rem' }}>Affiliate Links &amp; Sponsorships</h2>
        <p>
          The project does not participate in affiliate programs and receives no compensation from the organizations
          mentioned. If that changes, the disclosure will be updated here.
        </p>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem', marginTop: '1rem' }}>
          Last updated: 2026-05-26
        </p>
      </section>
    </div>
  );
}

export default Disclosures;
