import React from 'react';

function Disclosures() {
  return (
    <div className="card" style={{ maxWidth: '880px', margin: '0 auto' }}>
      <h1 style={{ marginBottom: '1rem' }}>Disclosures</h1>

      <section style={{ marginBottom: '1.75rem' }}>
        <h2 style={{ fontSize: '1.25rem' }}>AI-Generated Content</h2>
        <p style={{ marginBottom: '0.75rem' }}>
          All summaries, predictions, root-cause analyses, thread intelligence, and country briefings are generated
          by large language models. They are provided for informational and educational purposes only.
        </p>
        <p style={{ marginBottom: '0.75rem' }}>
          <strong>This content does not constitute financial, investment, legal, political, security, or professional
          advice of any kind.</strong> Forward-looking statements and forecasts reflect AI-generated analysis of
          available information and are not guarantees or predictions of future events. Actual outcomes may differ
          materially from anything described on this platform.
        </p>
        <p style={{ marginBottom: '0.75rem' }}>
          You should not rely solely on content from this platform when making business, investment, policy, or
          security decisions. Always verify information independently through primary sources and consult qualified
          professionals where appropriate.
        </p>
        <p>
          Global Perspectives assumes no liability for decisions made based on AI-generated content. Use of this
          platform constitutes acceptance of this disclaimer.
        </p>
      </section>

      <section style={{ marginBottom: '1.75rem' }}>
        <h2 style={{ fontSize: '1.25rem' }}>Limitation of Liability</h2>
        <p style={{ marginBottom: '0.75rem' }}>
          To the maximum extent permitted by applicable law, Global Perspectives and its operators shall not be
          liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use
          of this platform or reliance on any content it provides.
        </p>
        <p>
          The platform is provided "as is" without warranties of any kind, express or implied, including but not
          limited to accuracy, completeness, timeliness, or fitness for a particular purpose.
        </p>
      </section>

      <section style={{ marginBottom: '1.75rem' }}>
        <h2 style={{ fontSize: '1.25rem' }}>Data Sources</h2>
        <ul style={{ paddingLeft: '1.25rem' }}>
          <li>Topic detection and AI analysis: xAI Grok using globally syndicated publishers and Brave Search.</li>
          <li>Geocoding and map layers: Google Maps Platform.</li>
        </ul>
        <p style={{ marginTop: '0.75rem' }}>
          Source articles are linked for reference. Global Perspectives does not reproduce full article text and
          is not responsible for the accuracy or availability of third-party source content.
        </p>
      </section>

      <section style={{ marginBottom: '1.75rem' }}>
        <h2 style={{ fontSize: '1.25rem' }}>Economic Disruption Analysis</h2>
        <p style={{ marginBottom: '0.75rem' }}>
          <strong>This is not investment advice.</strong> The Economic Disruption layer attempts to identify
          which financial instruments are being repriced by ongoing news threads. It is provided for
          analytical context only, not for trading, investment, or portfolio decisions.
        </p>
        <p style={{ marginBottom: '0.75rem' }}>
          <strong>Methodology — what is generated by AI vs. computed:</strong>
        </p>
        <ul style={{ paddingLeft: '1.25rem', marginBottom: '0.75rem' }}>
          <li><strong>AI generates:</strong> direction (up/down/mixed), severity bands (minor/moderate/severe),
            magnitude bands (small/moderate/large), 1–2 paragraph mechanism narrative, historical-analog selection,
            and the list of relevant instruments — chosen from a fixed allowlist.</li>
          <li><strong>We compute from market data, not AI:</strong> actual price levels, asOf timestamps, and any
            observed % moves. Prices are snapshotted from public sources (Frankfurter / FRED / Stooq / World Bank).</li>
          <li><strong>Severity is never a percentage.</strong> We do not publish point estimates of price impact
            because LLMs are documented to hallucinate financial point estimates. Severity is expressed as a
            qualitative band only.</li>
          <li><strong>Every claim cites a topicId</strong> from the underlying news thread. Claims that cannot
            be cited to specific articles are dropped server-side.</li>
          <li><strong>Closed instrument allowlist.</strong> The AI may only reference instruments from a curated
            list of commodities, indices, ETFs, sovereign yields, FX pairs, and select crypto. Anything else
            is filtered out.</li>
          <li><strong>Historical analogs show realized past moves, not predictions.</strong> When an analog event
            is cited (e.g. "2019 Abqaiq attack"), we describe what historically happened — we do not predict the
            current outcome will match.</li>
        </ul>
        <p style={{ marginBottom: '0.75rem' }}>
          <strong>Limitations.</strong> Most short-term market moves are driven by macro flows (Fed policy, positioning,
          liquidity), not by the geopolitical headline of the day. Treat any "instrument moved on news X" framing
          as <em>consistent with</em>, not <em>caused by</em>. Outputs may be stale by hours; check the
          <code> asOf </code>timestamp on every record. References to academic methodology include
          Caldara &amp; Iacoviello (2022) Geopolitical Risk Index and the BlackRock Investment Institute's
          Geopolitical Risk Dashboard.
        </p>
      </section>

      <section style={{ marginBottom: '1.75rem' }}>
        <h2 style={{ fontSize: '1.25rem' }}>Accuracy &amp; Bias</h2>
        <p>
          AI systems can reflect the limitations and biases of their training data and source material. Regions
          with limited media coverage may appear underrepresented. AI-generated analysis may contain errors,
          omissions, or outdated information. Global Perspectives makes no representation that content is complete,
          current, or free from inaccuracy.
        </p>
      </section>

      <section style={{ marginBottom: '1.75rem' }}>
        <h2 style={{ fontSize: '1.25rem' }}>Subscription Terms</h2>
        <h3 style={{ fontSize: '1.05rem', marginTop: '1rem' }}>Plans &amp; Pricing</h3>
        <ul style={{ paddingLeft: '1.25rem' }}>
          <li><strong>Free</strong> — access to today's global topics and the interactive map. No account required.</li>
          <li><strong>Member ($15/month)</strong> — 7-day narrative archive, story arc intelligence, thread analysis, country briefings with AI-powered risk signals, and the weekly map with date playback.</li>
          <li><strong>Enterprise</strong> — everything in Member plus 30-day archive depth and priority data access. <a href="mailto:globalperspectives.app@gmail.com">Contact us</a> for pricing.</li>
        </ul>
        <p>All paid plans are billed monthly. Prices are in USD and exclude applicable taxes.</p>

        <h3 style={{ fontSize: '1.05rem', marginTop: '1rem' }}>Free Trial</h3>
        <p>New accounts receive a 14-day free trial of Member features automatically upon sign-up. No credit card is required to start the trial. After the trial period, continued access to paid features requires a subscription.</p>

        <h3 style={{ fontSize: '1.05rem', marginTop: '1rem' }}>Cancellation</h3>
        <p>
          You may cancel your subscription at any time from your Account page via the Customer Portal.
          Cancellation takes effect at the end of your current billing period — you retain access until then.
          No partial refunds are issued for unused time within a billing cycle.
        </p>

        <h3 style={{ fontSize: '1.05rem', marginTop: '1rem' }}>Refund Policy</h3>
        <p>
          Refunds are considered on a case-by-case basis within 7 days of a charge. To request a refund,
          email <a href="mailto:globalperspectives.app@gmail.com">globalperspectives.app@gmail.com</a> with
          your account email and the reason for the request. We aim to respond within 2 business days.
        </p>

        <h3 style={{ fontSize: '1.05rem', marginTop: '1rem' }}>Payment Processing</h3>
        <p>
          Payments are processed securely by <a href="https://stripe.com" target="_blank" rel="noopener noreferrer">Stripe</a>.
          We do not store your credit card details. All payment data is handled directly by Stripe in accordance with
          PCI DSS Level 1 compliance standards.
        </p>
      </section>

      <section style={{ marginBottom: '1.75rem' }}>
        <h2 style={{ fontSize: '1.25rem' }}>Contact</h2>
        <p>
          For billing questions, account issues, or general inquiries:<br />
          Email: <a href="mailto:globalperspectives.app@gmail.com">globalperspectives.app@gmail.com</a>
        </p>
        <p>
          Business name: Global Perspectives
        </p>
      </section>

      <section>
        <h2 style={{ fontSize: '1.25rem' }}>Affiliate Links &amp; Sponsorships</h2>
        <p>
          The project does not participate in affiliate programs and receives no compensation from the organizations
          mentioned. If that changes, the disclosure will be updated here.
        </p>
        <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem', marginTop: '1rem' }}>
          Last updated: 2026-03-21
        </p>
      </section>
    </div>
  );
}

export default Disclosures;
