'use strict';

// Render a breaking-news alert email from an already-assembled `story` object.
// Pure / no I/O so it can be previewed in the dry-run log and unit-tested. Returns
// { subject, text, html } — text is the always-safe fallback; html is the styled
// version (table layout + inline CSS, the only thing email clients render reliably).
//
// HONESTY CONTRACT: only render sections that actually have content. No placeholder
// copy, no fabricated urgency, no invented numbers. Every claim shown here was
// generated by the pipeline against real sources; we only format it.
//
//   story = {
//     title,                       // sharp story title (threadAnalysis.threadTitle || topic.title)
//     category, regions[],         // tags
//     threadUrl,                   // link to the thread deep-dive on the site
//     summary,                     // lead topic SUMMARY (bullet text) — optional
//     prediction,                  // lead topic PREDICTION text — optional
//     economic,                    // { direction, magnitude } — optional
//     sources: [{ title, url }],   // real article links
//     editorNote,                  // human-written commentary added at review time — optional
//     unsubscribeUrl,              // one-click unsubscribe (compliance) — optional
//   }

// Brand palette (matches the site's design tokens).
const C = {
  paper: '#fbfbf9',
  card: '#ffffff',
  ink: '#0a0a0a',
  accent: '#a2442e', // rust
  line: '#e5e5e3',
  muted: '#6b6b66',
};
const SERIF = "Georgia, 'Times New Roman', serif";
const SANS = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif";

function clean(s) {
  return typeof s === 'string' ? s.trim() : '';
}

function escapeHtml(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function directionArrow(dir) {
  return dir === 'up' ? '▲' : dir === 'down' ? '▼' : '◆';
}

// Normalize the structured TRACE_CAUSE object into the few fields worth showing in an
// alert: the 3-layer causal chain (trigger → building factors → structural root), the
// underreported angle, and the signal-vs-noise verdict. Returns null if nothing usable
// (so the section is omitted entirely — honesty contract).
function normalizeTrace(tc) {
  if (!tc || typeof tc !== 'object') return null;
  const trigger = clean(tc.proximate && tc.proximate.what);
  const when = clean(tc.proximate && tc.proximate.when);
  const building = (Array.isArray(tc.contributing) ? tc.contributing : [])
    .map((c) => ({ factor: clean(c && c.factor), evidence: clean(c && c.evidence) }))
    .filter((c) => c.factor)
    .slice(0, 2);
  const root = clean(tc.structural && tc.structural.factor);
  const depth = clean(tc.structural && tc.structural.depth);
  const altAngle = clean(tc.alternativePerspective);
  const verdict = clean(tc.signalVsNoise && tc.signalVsNoise.verdict);
  const confidence = clean(tc.signalVsNoise && tc.signalVsNoise.confidence);
  if (!trigger && !building.length && !root) return null;
  return { trigger, when, building, root, depth, altAngle, verdict, confidence };
}

function traceTextLines(tc) {
  const t = normalizeTrace(tc);
  if (!t) return [];
  const lines = ['HOW WE GOT HERE'];
  if (t.trigger) lines.push(`Trigger: ${t.trigger}${t.when ? ` (${t.when})` : ''}`);
  for (const b of t.building) lines.push(`Building: ${b.factor}${b.evidence ? ` — ${b.evidence}` : ''}`);
  if (t.root) lines.push(`Root cause: ${t.root}${t.depth ? ` (${t.depth})` : ''}`);
  if (t.altAngle) lines.push(`Underreported angle: ${t.altAngle}`);
  if (t.verdict) lines.push(`Signal vs noise: ${t.verdict}${t.confidence ? ` (${t.confidence} confidence)` : ''}`);
  return lines;
}

// ── Plain-text body (always-safe fallback) ──────────────────────────────────────
function renderText(story) {
  const title = clean(story.title) || 'A significant story is developing';
  const lines = [title];

  const tagBits = [];
  if (story.category) tagBits.push(story.category);
  if (Array.isArray(story.regions) && story.regions.length) tagBits.push(story.regions.slice(0, 4).join(', '));
  if (tagBits.length) lines.push(tagBits.join(' · '));
  lines.push('');

  const note = clean(story.editorNote);
  if (note) { lines.push(note); lines.push(''); }

  const summary = clean(story.summary);
  if (summary) { lines.push('WHAT HAPPENED'); lines.push(summary); lines.push(''); }

  const traceLines = traceTextLines(story.traceCause);
  if (traceLines.length) { lines.push(...traceLines); lines.push(''); }

  const prediction = clean(story.prediction);
  if (prediction) { lines.push('OUR READ — WHAT COMES NEXT'); lines.push(prediction); lines.push(''); }

  if (story.economic && story.economic.direction && story.economic.magnitude) {
    lines.push(`MARKET IMPACT: ${story.economic.magnitude} move, ${story.economic.direction}`);
    lines.push('');
  }

  if (story.threadUrl) { lines.push(`Full analysis: ${story.threadUrl}`); lines.push(''); }

  const sources = Array.isArray(story.sources) ? story.sources.filter((s) => s && s.url) : [];
  if (sources.length) {
    lines.push('SOURCES');
    for (const s of sources.slice(0, 6)) lines.push(`- ${clean(s.title) || s.url} — ${s.url}`);
    lines.push('');
  }

  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trim();
}

// ── HTML helpers ────────────────────────────────────────────────────────────────
function sectionLabel(txt) {
  return `<p style="margin:0 0 10px;font-family:${SANS};font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:${C.accent};">${escapeHtml(txt)}</p>`;
}

// Convert a markdown-ish block (some lines starting with "- ") into safe HTML.
function blockToHtml(text) {
  const all = String(text || '').split('\n').map((l) => l.trim()).filter(Boolean);
  if (!all.length) return '';
  const bullets = all.filter((l) => /^[-*]\s+/.test(l));
  if (bullets.length === all.length) {
    const items = all
      .map((l) => `<li style="margin:0 0 8px;">${escapeHtml(l.replace(/^[-*]\s+/, ''))}</li>`)
      .join('');
    return `<ul style="margin:0;padding:0 0 0 20px;color:${C.ink};font-family:${SANS};font-size:15px;line-height:1.55;">${items}</ul>`;
  }
  return all
    .map((l) => `<p style="margin:0 0 10px;color:${C.ink};font-family:${SANS};font-size:15px;line-height:1.6;">${escapeHtml(l)}</p>`)
    .join('');
}

function ctaButton(url) {
  // Table-based button — the only kind that renders across email clients.
  return `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:8px 0 4px;"><tr>
<td style="border-radius:6px;background:${C.accent};">
<a href="${escapeHtml(url)}" style="display:inline-block;padding:13px 22px;font-family:${SANS};font-size:15px;font-weight:700;color:#ffffff;text-decoration:none;border-radius:6px;">Read the full analysis &rarr;</a>
</td></tr></table>`;
}

// Trace-cause causal chain as HTML (returns '' when there's nothing usable).
function traceHtml(tc) {
  const t = normalizeTrace(tc);
  if (!t) return '';
  const row = (label, val) =>
    `<p style="margin:0 0 9px;font-family:${SANS};font-size:15px;line-height:1.5;color:${C.ink};"><span style="font-weight:700;color:${C.muted};">${label}:</span> ${escapeHtml(val)}</p>`;

  const rows = [];
  if (t.trigger) rows.push(row('Trigger', t.trigger + (t.when ? ` (${t.when})` : '')));
  for (const b of t.building) rows.push(row('Building', b.factor + (b.evidence ? ` — ${b.evidence}` : '')));
  if (t.root) rows.push(row('Root cause', t.root + (t.depth ? ` (${t.depth})` : '')));

  let altBox = '';
  if (t.altAngle) {
    altBox = `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:6px 0 2px;"><tr>
<td style="padding:11px 15px;background:#f4f5f3;border-left:3px solid ${C.muted};font-family:${SANS};font-size:14px;line-height:1.5;color:${C.ink};">
<span style="font-weight:700;color:${C.muted};">Underreported angle:</span> ${escapeHtml(t.altAngle)}</td></tr></table>`;
  }

  let signalChip = '';
  if (t.verdict) {
    signalChip = `<p style="margin:10px 0 0;"><span style="display:inline-block;padding:5px 11px;border:1px solid ${C.line};border-radius:6px;font-family:${SANS};font-size:12px;font-weight:700;color:${C.muted};">Signal vs noise: ${escapeHtml(t.verdict)}${t.confidence ? ` · ${escapeHtml(t.confidence)} confidence` : ''}</span></p>`;
  }

  return sectionLabel('How we got here') + rows.join('') + altBox + signalChip;
}

// ── HTML body ───────────────────────────────────────────────────────────────────
function renderHtml(story) {
  const title = clean(story.title) || 'A significant story is developing';
  const tagBits = [];
  if (story.category) tagBits.push(story.category);
  if (Array.isArray(story.regions) && story.regions.length) tagBits.push(story.regions.slice(0, 4).join(', '));
  const tagLine = tagBits.join(' · ');

  const note = clean(story.editorNote);
  const summary = clean(story.summary);
  const prediction = clean(story.prediction);
  const econ = story.economic && story.economic.direction && story.economic.magnitude ? story.economic : null;
  const sources = Array.isArray(story.sources) ? story.sources.filter((s) => s && s.url) : [];

  // Hidden preheader (inbox preview text).
  const preheader = (summary || prediction || title).replace(/^[-*]\s+/, '').slice(0, 140);

  const blocks = [];

  // Masthead
  blocks.push(`<tr><td style="padding:24px 32px 18px;border-bottom:1px solid ${C.line};">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
<td style="font-family:${SERIF};font-size:15px;font-weight:700;letter-spacing:.04em;color:${C.ink};text-transform:uppercase;">Global Perspectives</td>
<td align="right"><span style="display:inline-block;padding:4px 10px;border-radius:4px;background:${C.accent};font-family:${SANS};font-size:11px;font-weight:700;letter-spacing:.1em;color:#ffffff;">BREAKING</span></td>
</tr></table></td></tr>`);

  // Headline + tags
  blocks.push(`<tr><td style="padding:26px 32px 0;">
${tagLine ? `<p style="margin:0 0 10px;font-family:${SANS};font-size:12px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:${C.muted};">${escapeHtml(tagLine)}</p>` : ''}
<h1 style="margin:0;font-family:${SERIF};font-size:25px;line-height:1.25;font-weight:700;color:${C.ink};">${escapeHtml(title)}</h1>
</td></tr>`);

  // Editor note (the human's words) — accent left border
  if (note) {
    blocks.push(`<tr><td style="padding:18px 32px 0;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
<td style="padding:12px 16px;background:#faf3f1;border-left:3px solid ${C.accent};font-family:${SANS};font-size:15px;line-height:1.55;color:${C.ink};font-style:italic;">${escapeHtml(note)}</td>
</tr></table></td></tr>`);
  }

  if (summary) {
    blocks.push(`<tr><td style="padding:24px 32px 0;">${sectionLabel('What happened')}${blockToHtml(summary)}</td></tr>`);
  }

  const traceBlock = traceHtml(story.traceCause);
  if (traceBlock) {
    blocks.push(`<tr><td style="padding:24px 32px 0;">${traceBlock}</td></tr>`);
  }

  if (prediction) {
    blocks.push(`<tr><td style="padding:24px 32px 0;">${sectionLabel('Our read — what comes next')}${blockToHtml(prediction)}</td></tr>`);
  }

  if (econ) {
    blocks.push(`<tr><td style="padding:22px 32px 0;">
<span style="display:inline-block;padding:7px 13px;border:1px solid ${C.line};border-radius:6px;font-family:${SANS};font-size:13px;font-weight:700;color:${C.ink};">
${directionArrow(econ.direction)}&nbsp; Market impact: ${escapeHtml(econ.magnitude)} move, ${escapeHtml(econ.direction)}</span>
</td></tr>`);
  }

  if (story.threadUrl) {
    blocks.push(`<tr><td style="padding:24px 32px 0;">${ctaButton(story.threadUrl)}</td></tr>`);
  }

  if (sources.length) {
    const items = sources.slice(0, 6).map((s) =>
      `<p style="margin:0 0 7px;font-family:${SANS};font-size:13px;line-height:1.4;">
<a href="${escapeHtml(s.url)}" style="color:${C.accent};text-decoration:none;">${escapeHtml(clean(s.title) || s.url)}</a></p>`
    ).join('');
    blocks.push(`<tr><td style="padding:26px 32px 0;">${sectionLabel('Sources')}${items}</td></tr>`);
  }

  // Footer
  const unsub = story.unsubscribeUrl
    ? `<a href="${escapeHtml(story.unsubscribeUrl)}" style="color:${C.muted};text-decoration:underline;">Unsubscribe</a>`
    : 'You can unsubscribe any time from your account settings.';
  blocks.push(`<tr><td style="padding:30px 32px 28px;border-top:1px solid ${C.line};margin-top:24px;">
<p style="margin:0 0 6px;font-family:${SANS};font-size:12px;line-height:1.5;color:${C.muted};">You're receiving this because you subscribed to Global Perspectives breaking alerts.</p>
<p style="margin:0;font-family:${SANS};font-size:12px;line-height:1.5;color:${C.muted};">${unsub} &nbsp;·&nbsp; <a href="https://globalperspective.net" style="color:${C.muted};text-decoration:underline;">globalperspective.net</a></p>
</td></tr>`);

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="light"><title>${escapeHtml(title)}</title></head>
<body style="margin:0;padding:0;background:${C.paper};">
<span style="display:none!important;visibility:hidden;opacity:0;height:0;width:0;overflow:hidden;mso-hide:all;">${escapeHtml(preheader)}</span>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:${C.paper};">
<tr><td align="center" style="padding:24px 12px;">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px;max-width:600px;background:${C.card};border:1px solid ${C.line};border-radius:10px;overflow:hidden;">
${blocks.join('\n')}
</table>
</td></tr></table></body></html>`;
}

function renderAlert(story = {}) {
  const title = clean(story.title) || 'A significant story is developing';
  const subject = `Breaking: ${title}`.slice(0, 150);
  return { subject, text: renderText(story), html: renderHtml(story) };
}

module.exports = { renderAlert, _internals: { renderText, renderHtml, escapeHtml } };
